# Generated by Django 3.2.25 on 2026-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, help_text='Optional caption for this link', max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(help_text='YouTube, Vimeo, or any web link', max_length=255, verbose_name='URL'),
        ),
    ]
