# Generated by Django 3.2.25 on 2026-02-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20260204_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption (optional)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=255, verbose_name='URL (video, social media, photo album, article)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email (optional, not public)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Private message (optional, not public)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (required)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, verbose_name="Story or memory you'd like to share (required if no photos)"),
        ),
    ]
